name: Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install deb deps
      run: sudo apt install g++ make autoconf automake autopoint libtool
    - name: autoreconf
      run: autoreconf -vfi
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - make: package
      run: |
        cd src/tools/.libs/
        tar czf hunspell-linux-x64.tar.gz *
    - name: Upload hunspell-linux-x64.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: hunspell-linux-x64.tar.gz
          path: src/tools/.libs/hunspell-linux-x64.tar.gz
          
